version: '3.8'
services:
    app:
        build: .
        container_name: laravel_app
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./laravel.conf:/etc/apache2/sites-available/000-default.conf
        environment:
            APP_NAME: Laravel
            APP_ENV: local
            APP_DEBUG: "true"
            APP_URL: http://localhost:8000
            LOG_CHANNEL: stack
        depends_on:
            - db
            - redis

    db:
        image: mysql:5.7
        container_name: laravel_db
        restart: unless-stopped
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: wsmovies
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"
        restart: unless-stopped

volumes:
    dbdata:
